[package]
name = "solana-curve25519"
description = "Solana Curve25519 Syscalls"
documentation = "https://docs.rs/solana-curve25519"
version = "4.0.1"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
bytemuck = { workspace = true }
bytemuck_derive = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-ed25519 = { workspace = true, features = ["alloc", "serde"] }
# this crate uses `subtle::CtOption<Scalar>::into_option` via solana-ed25519,
# which requires subtle v2.6.1, but solana-ed25519 only requires v2.6.0
# The line below help users of this crate obtain correct subtle version.
# (that is, the version specified by our workspace or greater minor version, not the version specified by solana-ed25519)
subtle = { workspace = true }

[target.'cfg(target_os = "solana")'.dependencies]
solana-define-syscall = { workspace = true }

[lints]
workspace = true
